SystemOrganization addCategory: #'Brick-Experimental'!
SystemOrganization addCategory: 'Brick-Experimental-Dialog'!
SystemOrganization addCategory: 'Brick-Experimental-Examples'!
SystemOrganization addCategory: 'Brick-Experimental-Menu'!
SystemOrganization addCategory: 'Brick-Experimental-SidePane'!
SystemOrganization addCategory: 'Brick-Experimental-Toolbar'!
SystemOrganization addCategory: 'Brick-Experimental-Window'!
