SystemOrganization addCategory: #Brick!
SystemOrganization addCategory: 'Brick-!! Core'!
SystemOrganization addCategory: 'Brick-!! Core - Events'!
SystemOrganization addCategory: 'Brick-!! Core - Stencil'!
SystemOrganization addCategory: 'Brick-Button - UI'!
SystemOrganization addCategory: 'Brick-List - Events'!
SystemOrganization addCategory: 'Brick-List - Look'!
SystemOrganization addCategory: 'Brick-List - Model'!
SystemOrganization addCategory: 'Brick-List - Stencil'!
SystemOrganization addCategory: 'Brick-List - Support'!
SystemOrganization addCategory: 'Brick-List - UI'!
SystemOrganization addCategory: 'Brick-Pager - Events'!
SystemOrganization addCategory: 'Brick-Pager - Look'!
SystemOrganization addCategory: 'Brick-Pager - Model'!
SystemOrganization addCategory: 'Brick-Pager - Support'!
SystemOrganization addCategory: 'Brick-Pager - UI'!
SystemOrganization addCategory: 'Brick-Tabs - Events'!
SystemOrganization addCategory: 'Brick-Tabs - Look'!
SystemOrganization addCategory: 'Brick-Tabs - Model'!
SystemOrganization addCategory: 'Brick-Tabs - UI'!
SystemOrganization addCategory: 'Brick-Toggle - Events'!
SystemOrganization addCategory: 'Brick-Toggle - Look'!
SystemOrganization addCategory: 'Brick-Toggle - Model'!
SystemOrganization addCategory: 'Brick-Toggle - UI'!
SystemOrganization addCategory: 'Brick-Toolbar - Events'!
SystemOrganization addCategory: 'Brick-Toolbar - Look'!
SystemOrganization addCategory: 'Brick-Toolbar - Model'!
SystemOrganization addCategory: 'Brick-Toolbar - UI'!
SystemOrganization addCategory: 'Brick-UML - Stencil'!
