SystemOrganization addCategory: #'Brick-Style'!
SystemOrganization addCategory: 'Brick-Style-CSS'!
SystemOrganization addCategory: 'Brick-Style-EventListener'!
SystemOrganization addCategory: 'Brick-Style-Examples'!
SystemOrganization addCategory: 'Brick-Style-Styler'!
SystemOrganization addCategory: 'Brick-Style-Tests'!
SystemOrganization addCategory: 'Brick-Style-Util'!
SystemOrganization addCategory: 'Brick-Style-Value'!
