"
I am a strategy to find a target for opening a popup.

A target can be for example a separate window, a modal dialog or an arbitrary UI element
"
Class {
	#name : #BrPopupTarget,
	#superclass : #Object,
	#category : #'Brick-Popup - Model'
}

{ #category : #'api - popup' }
BrPopupTarget >> closePopup: aPopupElement [
	
]

{ #category : #'api - popup' }
BrPopupTarget >> openPopup: aPopupElement [
	
]
