"
!Adornments

The editor supports ''adornment'' attributes that visually influence the content of the editor. ${class:BrTextAdornmentAttribute}$ is the superclass of all adornment attributes.

Adornment attribute can replace a piece of text with arbitrary visual elements or simply append them after a piece of text. Therefore we define two groups of adornments:

# replacing ${class:BrTextEditorReplacingAdornmentsExamples}$
# appending ${class:BrTextEditorAppendingAdornmentsExamples}$
"
Class {
	#name : #BrTextEditorAdornmentsExamples,
	#superclass : #Object,
	#category : #'Brick-Editor-Examples-Documentation'
}
